/**
 * \file
 * \brief API implementation for the Kaa IoT broker.
 *
 * \copyright (c) 2025 Würth Elektronik eiSos GmbH & Co. KG
 *
 * \page License
 *
 * THE SOFTWARE INCLUDING THE SOURCE CODE IS PROVIDED “AS IS”. YOU ACKNOWLEDGE THAT WÜRTH ELEKTRONIK
 * EISOS MAKES NO REPRESENTATIONS AND WARRANTIES OF ANY KIND RELATED TO, BUT NOT LIMITED
 * TO THE NON-INFRINGEMENT OF THIRD PARTIES’ INTELLECTUAL PROPERTY RIGHTS OR THE
 * MERCHANTABILITY OR FITNESS FOR YOUR INTENDED PURPOSE OR USAGE. WÜRTH ELEKTRONIK EISOS DOES NOT
 * WARRANT OR REPRESENT THAT ANY LICENSE, EITHER EXPRESS OR IMPLIED, IS GRANTED UNDER ANY PATENT
 * RIGHT, COPYRIGHT, MASK WORK RIGHT, OR OTHER INTELLECTUAL PROPERTY RIGHT RELATING TO ANY
 * COMBINATION, MACHINE, OR PROCESS IN WHICH THE PRODUCT IS USED. INFORMATION PUBLISHED BY
 * WÜRTH ELEKTRONIK EISOS REGARDING THIRD-PARTY PRODUCTS OR SERVICES DOES NOT CONSTITUTE A LICENSE
 * FROM WÜRTH ELEKTRONIK EISOS TO USE SUCH PRODUCTS OR SERVICES OR A WARRANTY OR ENDORSEMENT
 * THEREOF
 *
 * THIS SOURCE CODE IS PROTECTED BY A LICENSE.
 * FOR MORE INFORMATION PLEASE CAREFULLY READ THE LICENSE AGREEMENT FILE LOCATED
 * IN THE ROOT DIRECTORY OF THIS PACKAGE
 */
 #ifndef KAAIOT_H
 #define KAAIOT_H
 #include <string.h>
 
 #include "json-builder.h"
 #include "device.h"
 #include "calypsoBoard.h"
 
 #ifdef __cplusplus
 extern "C"
 {
 #endif

#define KAA_TELEMETRY_PUBLISH_TOPIC "kp1/%s/dcx/%s/json"
#define KAA_COMMANDS_TOPIC "kp1/%s/cex/%s/command/#"
#define KAA_COMMANDS_RESPONSE_TOPIC "kp1/%s/cex/%s/result/%s"
 
 bool Kaa_loadConfiguration(json_value *configuration, CALYPSO *calypso);
 bool Kaa_SubscribeToTopics(CALYPSO *calypso);
 void Kaa_ProcessCloudMessage(json_value *cloudResponse, CALYPSO *calypso);
 
 #ifdef __cplusplus
 }
 #endif

 
 #endif //KAAIOT_H